- type: job
  id: Brigmedic
  name: Бригмедик
  description: Лечите павших бойцов сб! Лечите заключённых которых покалечели уже несколько раз выключенной дубинкой!
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000 #5 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 18000 #5 hrs
  startingGear: BrigmedicGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Medical
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]